version: '3'
services:
  solr:
    image: solr:latest
    container_name: skillhub-solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - users_core
volumes:
  solr_data: