name: Server Tests

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server-tests.yml"
  pull_request:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server-tests.yml"

jobs:
  test-server:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: apk add --no-cache python3 make g++ vips-dev

      - name: Install dependencies in server directory
        run: |
          cd server
          npm uninstall sharp
          npm install --platform=linux --arch=x64 --libc=musl
          npm rebuild sharp

      - name: Run tests in server directory
        run: npm test
        working-directory: ./server
